# numpy

In [1]:
import pandas as pd
import numpy as np

In [2]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"

In [3]:
df = pd.read_csv(url)
df.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [4]:
df.values

array([[16.99, 1.01, 'Female', ..., 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', ..., 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', ..., 'Sun', 'Dinner', 3],
       ...,
       [22.67, 2.0, 'Male', ..., 'Sat', 'Dinner', 2],
       [17.82, 1.75, 'Male', ..., 'Sat', 'Dinner', 2],
       [18.78, 3.0, 'Female', ..., 'Thur', 'Dinner', 2]],
      shape=(244, 7), dtype=object)

In [5]:
bill_np = df["total_bill"].to_numpy()

In [6]:
bill_np

array([16.99, 10.34, 21.01, 23.68, 24.59, 25.29,  8.77, 26.88, 15.04,
       14.78, 10.27, 35.26, 15.42, 18.43, 14.83, 21.58, 10.33, 16.29,
       16.97, 20.65, 17.92, 20.29, 15.77, 39.42, 19.82, 17.81, 13.37,
       12.69, 21.7 , 19.65,  9.55, 18.35, 15.06, 20.69, 17.78, 24.06,
       16.31, 16.93, 18.69, 31.27, 16.04, 17.46, 13.94,  9.68, 30.4 ,
       18.29, 22.23, 32.4 , 28.55, 18.04, 12.54, 10.29, 34.81,  9.94,
       25.56, 19.49, 38.01, 26.41, 11.24, 48.27, 20.29, 13.81, 11.02,
       18.29, 17.59, 20.08, 16.45,  3.07, 20.23, 15.01, 12.02, 17.07,
       26.86, 25.28, 14.73, 10.51, 17.92, 27.2 , 22.76, 17.29, 19.44,
       16.66, 10.07, 32.68, 15.98, 34.83, 13.03, 18.28, 24.71, 21.16,
       28.97, 22.49,  5.75, 16.32, 22.75, 40.17, 27.28, 12.03, 21.01,
       12.46, 11.35, 15.38, 44.3 , 22.42, 20.92, 15.36, 20.49, 25.21,
       18.24, 14.31, 14.  ,  7.25, 38.07, 23.95, 25.71, 17.31, 29.93,
       10.65, 12.43, 24.08, 11.69, 13.42, 14.26, 15.95, 12.48, 29.8 ,
        8.52, 14.52,

In [7]:
bill_np.ndim

1

In [8]:
bill_np.shape

(244,)

In [9]:
bill_np.dtype

dtype('float64')

In [10]:
bill_pd = df["total_bill"]

In [11]:
bill_np + 1

array([17.99, 11.34, 22.01, 24.68, 25.59, 26.29,  9.77, 27.88, 16.04,
       15.78, 11.27, 36.26, 16.42, 19.43, 15.83, 22.58, 11.33, 17.29,
       17.97, 21.65, 18.92, 21.29, 16.77, 40.42, 20.82, 18.81, 14.37,
       13.69, 22.7 , 20.65, 10.55, 19.35, 16.06, 21.69, 18.78, 25.06,
       17.31, 17.93, 19.69, 32.27, 17.04, 18.46, 14.94, 10.68, 31.4 ,
       19.29, 23.23, 33.4 , 29.55, 19.04, 13.54, 11.29, 35.81, 10.94,
       26.56, 20.49, 39.01, 27.41, 12.24, 49.27, 21.29, 14.81, 12.02,
       19.29, 18.59, 21.08, 17.45,  4.07, 21.23, 16.01, 13.02, 18.07,
       27.86, 26.28, 15.73, 11.51, 18.92, 28.2 , 23.76, 18.29, 20.44,
       17.66, 11.07, 33.68, 16.98, 35.83, 14.03, 19.28, 25.71, 22.16,
       29.97, 23.49,  6.75, 17.32, 23.75, 41.17, 28.28, 13.03, 22.01,
       13.46, 12.35, 16.38, 45.3 , 23.42, 21.92, 16.36, 21.49, 26.21,
       19.24, 15.31, 15.  ,  8.25, 39.07, 24.95, 26.71, 18.31, 30.93,
       11.65, 13.43, 25.08, 12.69, 14.42, 15.26, 16.95, 13.48, 30.8 ,
        9.52, 15.52,

In [12]:
bill_pd + 1

0      17.99
1      11.34
2      22.01
3      24.68
4      25.59
       ...  
239    30.03
240    28.18
241    23.67
242    18.82
243    19.78
Name: total_bill, Length: 244, dtype: float64

In [13]:
bill_np * 1.07

array([18.1793, 11.0638, 22.4807, 25.3376, 26.3113, 27.0603,  9.3839,
       28.7616, 16.0928, 15.8146, 10.9889, 37.7282, 16.4994, 19.7201,
       15.8681, 23.0906, 11.0531, 17.4303, 18.1579, 22.0955, 19.1744,
       21.7103, 16.8739, 42.1794, 21.2074, 19.0567, 14.3059, 13.5783,
       23.219 , 21.0255, 10.2185, 19.6345, 16.1142, 22.1383, 19.0246,
       25.7442, 17.4517, 18.1151, 19.9983, 33.4589, 17.1628, 18.6822,
       14.9158, 10.3576, 32.528 , 19.5703, 23.7861, 34.668 , 30.5485,
       19.3028, 13.4178, 11.0103, 37.2467, 10.6358, 27.3492, 20.8543,
       40.6707, 28.2587, 12.0268, 51.6489, 21.7103, 14.7767, 11.7914,
       19.5703, 18.8213, 21.4856, 17.6015,  3.2849, 21.6461, 16.0607,
       12.8614, 18.2649, 28.7402, 27.0496, 15.7611, 11.2457, 19.1744,
       29.104 , 24.3532, 18.5003, 20.8008, 17.8262, 10.7749, 34.9676,
       17.0986, 37.2681, 13.9421, 19.5596, 26.4397, 22.6412, 30.9979,
       24.0643,  6.1525, 17.4624, 24.3425, 42.9819, 29.1896, 12.8721,
       22.4807, 13.3

In [14]:
bill_pd * 1.07

0      18.1793
1      11.0638
2      22.4807
3      25.3376
4      26.3113
        ...   
239    31.0621
240    29.0826
241    24.2569
242    19.0674
243    20.0946
Name: total_bill, Length: 244, dtype: float64

In [15]:
tip_np = df["tip"].to_numpy()

In [16]:
tip_pd = df["tip"]

In [18]:
tip_np / bill_np

array([0.05944673, 0.16054159, 0.16658734, 0.13978041, 0.14680765,
       0.18623962, 0.22805017, 0.11607143, 0.13031915, 0.21853857,
       0.16650438, 0.14180374, 0.10181582, 0.16277808, 0.20364127,
       0.18164968, 0.16166505, 0.22774708, 0.20624632, 0.1622276 ,
       0.22767857, 0.13553475, 0.14140774, 0.19228818, 0.160444  ,
       0.13138686, 0.14958863, 0.15760441, 0.19815668, 0.15267176,
       0.15183246, 0.13623978, 0.19920319, 0.11841469, 0.18391451,
       0.14962594, 0.12262416, 0.18133491, 0.12359551, 0.15989767,
       0.13965087, 0.14547537, 0.2195122 , 0.13636364, 0.18421053,
       0.16402406, 0.22492128, 0.18518519, 0.07180385, 0.16629712,
       0.19936204, 0.2526725 , 0.14938236, 0.15694165, 0.16979656,
       0.18009236, 0.0789266 , 0.05679667, 0.15658363, 0.13942407,
       0.15820601, 0.14482259, 0.17967332, 0.20557682, 0.15008528,
       0.15687251, 0.15015198, 0.3257329 , 0.09935739, 0.13924051,
       0.16389351, 0.17574692, 0.11690246, 0.19778481, 0.14935

In [17]:
tip_pd / bill_pd

0      0.059447
1      0.160542
2      0.166587
3      0.139780
4      0.146808
         ...   
239    0.203927
240    0.073584
241    0.088222
242    0.098204
243    0.159744
Length: 244, dtype: float64

In [20]:
bill_np[bill_np > 20]

array([21.01, 23.68, 24.59, 25.29, 26.88, 35.26, 21.58, 20.65, 20.29,
       39.42, 21.7 , 20.69, 24.06, 31.27, 30.4 , 22.23, 32.4 , 28.55,
       34.81, 25.56, 38.01, 26.41, 48.27, 20.29, 20.08, 20.23, 26.86,
       25.28, 27.2 , 22.76, 32.68, 34.83, 24.71, 21.16, 28.97, 22.49,
       22.75, 40.17, 27.28, 21.01, 44.3 , 22.42, 20.92, 20.49, 25.21,
       38.07, 23.95, 25.71, 29.93, 24.08, 29.8 , 22.82, 20.27, 34.3 ,
       41.19, 27.05, 24.55, 29.85, 48.17, 25.  , 21.5 , 24.52, 20.76,
       31.71, 50.81, 31.85, 32.9 , 34.63, 34.65, 23.33, 45.35, 23.17,
       40.55, 20.69, 20.9 , 30.46, 23.1 , 28.44, 43.11, 20.53, 26.59,
       38.73, 24.27, 30.06, 25.89, 48.33, 28.17, 28.15, 30.14, 20.45,
       22.12, 24.01, 32.83, 35.83, 29.03, 27.18, 22.67])

In [21]:
np.mean(bill_np)

np.float64(19.78594262295082)

In [22]:
bill_pd.mean()

np.float64(19.78594262295082)

In [23]:
np.median(bill_np)

np.float64(17.795)

In [24]:
bill_pd.median()

np.float64(17.795)

In [25]:
np.std(bill_np)

np.float64(8.884150577771132)

In [26]:
bill_pd.std()

np.float64(8.902411954856856)

In [27]:
np.min(bill_np)

np.float64(3.07)

In [28]:
bill_pd.min()

np.float64(3.07)

In [29]:
np.max(bill_np)

np.float64(50.81)

In [30]:
bill_pd.max()

np.float64(50.81)

In [32]:
np.sort(bill_np)

array([ 3.07,  5.75,  7.25,  7.25,  7.51,  7.56,  7.74,  8.35,  8.51,
        8.52,  8.58,  8.77,  9.55,  9.6 ,  9.68,  9.78,  9.94, 10.07,
       10.07, 10.09, 10.27, 10.29, 10.33, 10.33, 10.34, 10.34, 10.51,
       10.59, 10.63, 10.65, 10.77, 11.02, 11.17, 11.24, 11.35, 11.38,
       11.59, 11.61, 11.69, 11.87, 12.02, 12.03, 12.16, 12.26, 12.43,
       12.46, 12.48, 12.54, 12.6 , 12.66, 12.69, 12.74, 12.76, 12.9 ,
       13.  , 13.  , 13.03, 13.13, 13.16, 13.27, 13.28, 13.37, 13.39,
       13.42, 13.42, 13.42, 13.51, 13.81, 13.81, 13.94, 14.  , 14.07,
       14.15, 14.26, 14.31, 14.48, 14.52, 14.73, 14.78, 14.83, 15.01,
       15.04, 15.06, 15.36, 15.38, 15.42, 15.48, 15.53, 15.69, 15.69,
       15.77, 15.81, 15.95, 15.98, 15.98, 16.  , 16.04, 16.21, 16.27,
       16.29, 16.31, 16.32, 16.4 , 16.43, 16.45, 16.47, 16.49, 16.58,
       16.66, 16.82, 16.93, 16.97, 16.99, 17.07, 17.26, 17.29, 17.31,
       17.46, 17.47, 17.51, 17.59, 17.78, 17.81, 17.82, 17.89, 17.92,
       17.92, 18.04,

In [31]:
bill_pd.sort_values()

67      3.07
92      5.75
111     7.25
172     7.25
149     7.51
       ...  
182    45.35
156    48.17
59     48.27
212    48.33
170    50.81
Name: total_bill, Length: 244, dtype: float64

In [33]:
bill_np = bill_np * (1.01 ** 1000)

In [34]:
bill_np

array([ 356096.05428646,  216717.669295  ,  440351.85995047,
        496312.80550343,  515385.63713384,  530057.04608031,
        183811.79494363,  563382.10354444,  315225.70079272,
        309776.32032689,  215250.52840035,  739019.82778932,
        323190.17993509,  386277.23840491,  310824.27810878,
        452298.57866402,  216508.07773862,  341424.64533999,
        355676.8711737 ,  432806.56392086,  375588.06902962,
        425261.26789124,  330525.88440832,  826209.91524262,
        415410.46474147,  373282.56190946,  280223.91087757,
        265971.68504386,  454813.67734056,  411847.40828304,
        200159.93634112,  384600.50595388,  315644.88390548,
        433644.93014637,  372653.78724033,  504277.2846458 ,
        341843.82845274,  354838.50494819,  391726.61887074,
        655392.79679444,  336184.85643053,  365946.85743623,
        292170.62959113,  202884.62657404,  637158.33138954,
        383342.95661562,  465922.0298286 ,  679076.64266517,
        598383.89345959,

In [35]:
for _ in range(1000):
    bill_pd = bill_pd * 1.01

In [36]:
bill_pd

0      356096.054286
1      216717.669295
2      440351.859950
3      496312.805503
4      515385.637134
           ...      
239    608444.288166
240    569669.850236
241    475144.058309
242    373492.153466
243    393612.942878
Name: total_bill, Length: 244, dtype: float64